version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgresdb'
      PGDATA: '/var/lib/psql/data/db/'
    ports:
      - 5432:5432
    volumes:
      - ./.data/db/postgres:/var/lib/postgresql/data
    env_file:
      - .env

  python:
    build: .
    restart: always
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres