# Generated by Django 4.2.4 on 2023-09-02 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Зміст')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата останніх змін')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['id', 'time_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_orderd', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(blank=True, default=False, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['date_orderd'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=128, null=True, verbose_name="Ім'я")),
                ('lastname', models.CharField(max_length=128, null=True, verbose_name='Прізвище')),
                ('delivery', models.CharField(choices=[('Нова пошта', 'Нова пошта'), ('Укрпошта', 'Укрпошта')], max_length=128, null=True, verbose_name='Спосіб доставки')),
                ('post_department', models.IntegerField(null=True, verbose_name='Номер відділення')),
                ('city', models.CharField(max_length=128, null=True, verbose_name='Населений пункт')),
                ('region', models.CharField(max_length=128, null=True, verbose_name='Область')),
                ('phoneNumber', models.IntegerField(null=True, verbose_name='Контактний номер')),
                ('comment', models.CharField(blank=True, max_length=400, null=True, verbose_name='Коментар до замовлення')),
                ('payment', models.CharField(choices=[('Передплата на карту ПриватБанк', 'Передплата на карту ПриватБанк'), ('Готівка при отриманні (тiльки для замовлень вiд 100 грн.)', 'Готівка при отриманні (тiльки для замовлень вiд 100 грн.)')], max_length=128, null=True, verbose_name='Спосіб оплати')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Дані про замовлення',
                'verbose_name_plural': 'Дані про замовлення',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Зображення')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Вартість')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Час зміни')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Є в наявності')),
                ('variant', models.BooleanField(default=False, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['id', 'title', 'time_create'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
            options={
                'verbose_name': 'Товар в замовленні',
                'verbose_name_plural': 'Товари в замовленні',
                'ordering': ['date_added'],
            },
        ),
    ]
